"""models

Revision ID: b8b6a26fa480
Revises: 9e627228c861
Create Date: 2025-12-09 05:18:41.630889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8b6a26fa480'
down_revision: Union[str, Sequence[str], None] = '9e627228c861'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('big_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('league',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_league_date', sa.DateTime(), nullable=False),
    sa.Column('format', sa.Enum('CHILL', 'SOFT', 'NORMAL', name='leagueformat'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roadmap',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('tag', sa.String(), nullable=True),
    sa.Column('custom', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('tag', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_id', sa.Integer(), nullable=False),
    sa.Column('tg_nickname', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bad_habits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('in_progress', sa.BOOLEAN(), nullable=False),
    sa.Column('completed', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('roadmap_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('tag', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmap.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('big_goal_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('usual', sa.BOOLEAN(), nullable=True),
    sa.Column('difficult', sa.Enum('VERY_EASY', 'EASY', 'NORMAL', 'HARD', 'INSANE', name='goalsdifficult'), nullable=False),
    sa.ForeignKeyConstraint(['big_goal_id'], ['big_goals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('href', sa.String(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('tag', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('league_big_goals',
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('big_goals_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['big_goals_id'], ['big_goals.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['league.id'], ),
    sa.PrimaryKeyConstraint('league_id', 'big_goals_id')
    )
    op.create_table('meds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dose', sa.String(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('daytime', sa.Enum('BEFORE_BREAKFAST', 'BREAKFAST', 'AFTER_BREAKFAST', 'BEFORE_LUNCH', 'LUNCH', 'AFTER_LUNCH', 'DINNER', 'BEFORE_DINNER', 'AFTER_DINNER', name='medsdaytime'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.TEXT(), nullable=True),
    sa.Column('tag', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_big_goals',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('big_goals_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['big_goals_id'], ['big_goals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'big_goals_id')
    )
    op.create_table('user_roadmaps',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('roadmap_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmap.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'roadmap_id')
    )
    op.create_table('bad_habit_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('daily_report', sa.String(), nullable=False),
    sa.Column('bad_habit_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bad_habit_id'], ['bad_habits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('league_goals',
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('goals_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['goals_id'], ['goals.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['league.id'], ),
    sa.PrimaryKeyConstraint('league_id', 'goals_id')
    )
    op.create_table('user_goals',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('goals_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['goals_id'], ['goals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'goals_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_goals')
    op.drop_table('league_goals')
    op.drop_table('bad_habit_stats')
    op.drop_table('user_roadmaps')
    op.drop_table('user_big_goals')
    op.drop_table('notes')
    op.drop_table('meds')
    op.drop_table('league_big_goals')
    op.drop_table('information')
    op.drop_table('goals')
    op.drop_table('classes')
    op.drop_table('bad_habits')
    op.drop_table('user')
    op.drop_table('tasks')
    op.drop_table('roadmap')
    op.drop_table('league')
    op.drop_table('big_goals')
    # ### end Alembic commands ###
