"""fixes in user, goals, tasks, big_goals

Revision ID: b9d14461cf7b
Revises: f87fc22ba020
Create Date: 2025-12-11 07:14:24.908999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9d14461cf7b'
down_revision: Union[str, Sequence[str], None] = 'f87fc22ba020'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('big_goals', sa.Column('completed', sa.BOOLEAN(), nullable=False))
    op.add_column('goals', sa.Column('completed', sa.BOOLEAN(), nullable=False))
    op.add_column('league', sa.Column('active', sa.BOOLEAN(), nullable=False))
    op.add_column('league', sa.Column('ended', sa.BOOLEAN(), nullable=False))
    op.add_column('tasks', sa.Column('completed', sa.BOOLEAN(), nullable=False))

    # УДАЛИТЬ или закомментировать проблемную строку для SQLite
    # op.alter_column('tasks', 'user_id', existing_type=sa.INTEGER(), nullable=False)

    op.add_column('user', sa.Column('is_active', sa.BOOLEAN(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_active')

    # УДАЛИТЬ или закомментировать
    # op.alter_column('tasks', 'user_id', existing_type=sa.INTEGER(), nullable=True)

    op.drop_column('tasks', 'completed')
    op.drop_column('league', 'ended')
    op.drop_column('league', 'active')
    op.drop_column('goals', 'completed')
    op.drop_column('big_goals', 'completed')
    # ### end Alembic commands ###